version: '3'

services:
  # mysql -h host -P port -uuser -ppass
  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
    - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}